apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend
  namespace: expense
  labels:  
    app: frontendend
    project: expense
    tier: web
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: frontend
      project: expense
      tier: web
  template:   
    metadata: 
      labels:  
        app: frontend
        project: expense
        tier: web
    spec: 
      containers: 
      - name: frontend
        image: # give image you pushed to dockerhub
        ports: 
        - containerPort: 80 # optional
        

---
apiVersion: v1 
kind: Service 
metadata: 
  name: frontend
  namespace: expense
spec: 
  type: LoadBalancer
  selector: 
    app: frontend
    project: expense
    tier: web
  ports:
  - name: frontend-port
    protocol: TCP
    port: 80 # service port
    targetPort: 80 # container port+
