apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: backend 
  namespace: expense
data: 
  DB_HOST: mysql
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:  
    app: backend
    project: expense
    tier: api
spec:
  replicas: 2
  selector: 
    matchLabels: 
      app: backend
      project: expense
      tier: api
  template:   
    metadata: 
      labels:  
        app: backend
        project: expense
        tier: api
    spec: 
      containers: 
      - name: backend
        image: # give image you pushed to dockerhub
        ports: 
        - containerPort: 8080 # optional
        envFrom: 
        - configMapRef: 
            name: backend 

---
apiVersion: v1 
kind: Service 
metadata: 
  name: backend
  namespace: expense
spec: 
  selector: 
    app: backend
    project: expense
    tier: api
  ports:
  - name: backend-port
    protocol: TCP
    port: 8080 # service port
    targetPort: 8080 # container port+
