apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels:  
    app: mysql 
    project: expense
    tier: db 
spec:
  replicas: 1
  selector: 
    matchLabels: 
      app: mysql 
      project: expense
      tier: db
  template:   
    metadata: 
      labels:  
        app: mysql 
        project: expense
        tier: db
    spec: 
      containers: 
      - name: mysql
        image: # give image you pushed to dockerhub
        ports: 
        - containerPort: 3306 # optional
---
apiVersion: v1 
kind: Service 
metadata: 
  name: mysql
  namespace: expense
spec: 
  selector: 
    app: mysql 
    project: expense
    tier: db
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # service port
    targetPort: 3306 # container port+
